using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Qread.Internals;

namespace Qread.Sources;

internal static class GenerateDataReaderAttribute
{
    public static IncrementalGeneratorPostInitializationContext AddGenerateDataReaderAttributeSource(
        this IncrementalGeneratorPostInitializationContext context
    )
    {
        context.AddSource(
            $"{nameof(Qread.GenerateDataReaderAttribute)}.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated />
                #nullable enable

                #if !QREAD_EXCLUDE_STD_CLASSES

                namespace {{Constants.Namespace}};

                [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false)]
                public sealed class {{nameof(Qread.GenerateDataReaderAttribute)}} : System.Attribute
                {
                    public bool IsExact { get; set; }
                }

                #endif

                """,
                Encoding.UTF8
            )
        );
        return context;
    }
}
