using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Qread.Internals;

namespace Qread.Sources;

internal static class GenerateDataReaderAttribute
{
    public const string Name = "GenerateDataReaderAttribute";

    public static IncrementalGeneratorPostInitializationContext AddGenerateDataReaderAttributeSource(
        this IncrementalGeneratorPostInitializationContext context
    )
    {
        context.AddSource(
            "GenerateDataReaderAttribute.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated />
                #nullable enable

                namespace {{Constants.Namespace}};

                [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false)]
                public sealed class {{Name}} : System.Attribute
                {
                    public bool IsExact { get; set; }
                }
                
                """,
                Encoding.UTF8
            )
        );
        return context;
    }
}
