using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Qread.Internals;

namespace Qread.Sources;

internal static class IgnoreAttribute
{
    public const string Name = "IgnoreAttribute";

    public static IncrementalGeneratorPostInitializationContext AddIgnoreAttributeSource(
        this IncrementalGeneratorPostInitializationContext context
    )
    {
        context.AddSource(
            $"{Name}.g.cs",
            SourceText.From(
                $"""
                // <auto-generated />
                #nullable enable

                namespace {Constants.Namespace};

                [System.AttributeUsage(System.AttributeTargets.Property, AllowMultiple = false)]
                internal sealed class {Name} : System.Attribute;
                
                """,
                Encoding.UTF8
            )
        );
        return context;
    }
}
