using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Qread.Internals;

namespace Qread.Sources;

internal static class TypeReaders
{
    public static IncrementalGeneratorPostInitializationContext AddTypeReadersSource(
        this IncrementalGeneratorPostInitializationContext context
    )
    {
        context.AddSource(
            "ITypeReader.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated />
                #nullable enable

                #if !QREAD_EXCLUDE_STD_CLASSES

                using System.Data;

                namespace {{Constants.Namespace}};

                public interface ITypeReader
                {
                    object? Read(IDataReader reader, int index);
                }

                #endif
                
                """,
                Encoding.UTF8
            )
        );
        context.AddSource(
            "TypeReader.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated />
                #nullable enable

                using System.Data;

                namespace {{Constants.Namespace}};

                public abstract class TypeReader<T> : ITypeReader
                {
                    public abstract T Read(IDataReader reader, int index);
                    
                    object? ITypeReader.Read(IDataReader reader, int index) => Read(reader, index);
                }
                
                """,
                Encoding.UTF8
            )
        );
        context.AddSource(
            "TypeReaders.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated />
                #nullable enable

                using System.Diagnostics.CodeAnalysis;

                namespace {{Constants.Namespace}};

                public static class TypeReaders
                {
                    private static readonly Dictionary<Type, ITypeReader> _readers = [];
                    
                    public static void AddReader<T>(TypeReader<T> reader) =>
                        _readers[typeof(T)] = reader;

                    internal static bool TryGetReader<T>([NotNullWhen(true)] out TypeReader<T>? reader)
                    {
                        reader = null;
                        
                        if (!_readers.TryGetValue(typeof(T), out var readerBase))
                            return false;
                        
                        reader = (TypeReader<T>)readerBase;
                        return true;
                    }
                }
                
                """,
                Encoding.UTF8
            )
        );
        return context;
    }
}
