//HintName: TestNamespace.Test2Dto.g.cs
// <auto-generated />
#nullable enable
using System.Collections.Frozen;
using System.Data;

namespace TestNamespace;

partial record Test2Dto
{
    private Test2Dto() { }

    public static global::TestNamespace.Test2Dto FromDataReader(IDataReader reader)
    {
        var propIndices = new Dictionary<string, int>(reader.FieldCount);

        for (var i = reader.FieldCount - 1; i >= 0; i--)
        {
            var columnName = reader.GetName(i);
            propIndices[columnName] = i;
        }

        return FromDataReader(reader, propIndices, null)!;
    }

    public static global::TestNamespace.Test2Dto? FromDataReader(IDataReader reader, Dictionary<string, int> propIndices, string? prefix)
    {
        var test = global::TestNamespace.TestDto.FromDataReader(reader, propIndices, $"{prefix}Test_");

        if (test is null)
            return null;

        var instance = new global::TestNamespace.Test2Dto
        {
            Test = test
        };
        return instance;
    }

    public static async IAsyncEnumerable<global::TestNamespace.Test2Dto> AsyncEnumerableFromDataReader(global::System.Data.IDataReader reader, [global::System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var dbReader = reader as global::System.Data.Common.DbDataReader;

        while (await ReadAsync())
        {
            var instance = FromDataReader(reader);
            yield return instance;
        }

        async ValueTask<bool> ReadAsync()
        {
            return dbReader is not null
                ? await dbReader.ReadAsync(cancellationToken)
                : reader.Read();
        }
    }
}
