//HintName: TestNamespace.TestDto.g.cs
// <auto-generated />
#nullable enable

using System.Data;

namespace TestNamespace;

partial record TestDto
{
    public static global::TestNamespace.TestDto FromDataReader(IDataReader reader)
    {
        var instance = new global::TestNamespace.TestDto
        {
            IsDisabled = global::Qread.TypeReaders.TryGetReader<bool>(out var readerIsDisabled) ? readerIsDisabled.Read(reader, 0) : reader.GetBoolean(0),
            IsDisabled2 = global::Qread.TypeReaders.TryGetReader<Boolean>(out var readerIsDisabled2) ? readerIsDisabled2.Read(reader, 1) : reader.GetBoolean(1)
        };
        return instance;
    }

    public static async IAsyncEnumerable<global::TestNamespace.TestDto> AsyncEnumerableFromDataReader(global::System.Data.IDataReader reader, [global::System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var dbReader = reader as global::System.Data.Common.DbDataReader;

        while (await ReadAsync())
        {
            var instance = FromDataReader(reader);
            yield return instance;
        }

        async ValueTask<bool> ReadAsync()
        {
            return dbReader is not null
                ? await dbReader.ReadAsync(cancellationToken)
                : reader.Read();
        }
    }
}
