//HintName: IgnoreAttribute.g.cs
// <auto-generated />
#nullable enable

namespace Qread;

[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false)]
internal sealed class IgnoreAttribute : System.Attribute;
