//HintName: TestNamespace.TestDto.g.cs
// <auto-generated />
#nullable enable

using System.Data;

namespace TestNamespace;

partial record TestDto
{
    public static global::TestNamespace.TestDto FromDataReader(IDataReader reader)
    {
        var instance = new global::TestNamespace.TestDto
        {
            Value = reader.GetFloat(0),
            Value2 = reader.GetFloat(1)
        };
        return instance;
    }

    public static IReadOnlyList<global::TestNamespace.TestDto> ListFromDataReader(IDataReader reader)
    {
        var results = new List<global::TestNamespace.TestDto>();

        while (reader.Read())
        {
            var instance = FromDataReader(reader);
            results.Add(instance);
        }

        return results;
    }
}
