//HintName: TestNamespace.TestDto.g.cs
// <auto-generated />
#nullable enable
using System.Collections.Frozen;
using System.Data;

namespace TestNamespace;

partial record TestDto
{
    private static FrozenDictionary<string, int>? _propIndices;

    public static TestDto FromDataReader(IDataReader reader)
    {
        if (_propIndices is null)
        {
            var unfrozenPropIndices = new Dictionary<string, int>();

            for (var i = reader.FieldCount - 1; i >= 0; i--)
            {
                var columnName = reader.GetName(i);
                unfrozenPropIndices[columnName] = i;
            }

            _propIndices = unfrozenPropIndices.ToFrozenDictionary();
        }

        var instance = new TestDto
        {
            Name = reader.GetString(_propIndices["Name"])
        };
        return instance;
    }

    public static IReadOnlyList<TestDto> ListFromDataReader(IDataReader reader)
    {
        var results = new List<TestDto>();

        while (reader.Read())
        {
            var instance = FromDataReader(reader);
            results.Add(instance);
        }

        return results;
    }
}
