//HintName: TestNamespace.ITest.TestDto.g.cs
// <auto-generated />
#nullable enable

using System.Data;

namespace TestNamespace;

partial interface ITest
{
    partial record struct TestDto
    {
        public static global::TestNamespace.ITest.TestDto FromDataReader(IDataReader reader)
        {
            var i = -1;
            var instance = new global::TestNamespace.ITest.TestDto
            {
            };
            return instance;
        }

        public static IReadOnlyList<global::TestNamespace.ITest.TestDto> ListFromDataReader(IDataReader reader)
        {
            var results = new List<global::TestNamespace.ITest.TestDto>();

            while (reader.Read())
            {
                var instance = FromDataReader(reader);
                results.Add(instance);
            }

            return results;
        }
    }
}
